### ISSUE TITLE
Banner:Responsive Error  - cropped

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/JC-Glass#15]
below 1366 viewport

![image](https://cloud.githubusercontent.com/assets/17717843/14077101/b994476e-f51a-11e5-8c63-e0e2b7cb70bd.png)

**Comment by henrytitan** [comment]
This is the nearest possible layout same to the approved design.

**Comment by dremensayson** [comment]
based on the standard, make the banner responsive. Position the banner after the header then position the banner content below the banner image.
